config/routes.rb
Rails.application.routes.draw do
#####################ログイン#####################
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
######################トップ######################
  get "/" => "home#top"
  get "/description" => "home#description"
  get "/opinion" => "home#opinion"
  post "/opinion" => "home#sendopinion"
#####################放送検索#####################
  get "/tool/search" => "tool#search" , as: "search"
  get "/tool/counter" => "tool#counter" , as: "counter"
#####################ユーザー#####################
  get "/user/:id" => "user#profile"
  get "/user/:id/edit" => "user#edit"
  post "/user/:id/update" => "user#update"
  post "/user/:id/update_password" => "user#update_password"
#######################解説#######################
  get "/explain/:dungeon" =>"explain#top"
  get "/explain/:dungeon/:id" =>"explain#explain"
  get "/explain/:dungeon/:id/edit" => "explain#edit"
  get "/explain/:dungeon/:id/edit/preview" => "explain#preview"
####################ランキング####################
  get "/ranking" => redirect {"/"}, as: "ranking"
  post "/ranking" => "ranking#create"
  get "/ranking/newrecord" => "ranking#newrecord", as: "newrecord"
  post "/ranking/newrecord" => "ranking#recordconfirm"
  get "/ranking/description" => "ranking#description"
  get "/ranking/:dungeon" => "ranking#dungeon"
  post "/ranking/:dungeon" =>"ranking#dungeon"
  get  "/ranking/:dungeon/:yyyymm" =>"ranking#dungeon"
  post "/ranking/:dungeon/:yyyymm" =>"ranking#dungeon"
#####################過去大会#####################
  # get "/historys" => "historys#tournaments"
######################クイズ######################
  # get "/quiz" => "quiz#quiz"
######################サイトマップ######################
  get 'sitemap.xml', to: redirect('https://s3-ap-northeast-1.amazonaws.com/shiren2records/sitemaps/sitemap.xml.gz')
end

app/views/layouts/_navbar_top.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="/">
        <%= image_tag image_url('headfoot/logo.png'), { :class => "logo", :alt => "風来のシレン2タイムアタック番付" ,:title => "風来のシレン2タイムアタック番付", :width => 120} %>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#headerData"
        aria-controls="headerData" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="headerData">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <%= link_to "放送検索", search_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="/" id="dropdown_tool" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">ツール</a>
                <div class="dropdown-menu" aria-labelledby="dropdown_tool">
                    <%= link_to "お城素材カウンター", counter_path , class: "dropdown-item" %>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="/" id="dropdown_desc" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">解説</a>
                <div class="dropdown-menu" aria-labelledby="dropdown_desc">
                    <%= link_to "最果てへの道99FTA","/explain/saihate" , class: "dropdown-item"%>
                    <%= link_to "カラクロTA", "/explain/well" , class: "dropdown-item"%>
                    <%= link_to "鬼ヶ島ありありTA", "/explain/onigashima" , class: "dropdown-item"%>
                    <%= link_to "ストーリーTA", "/explain/story" , class: "dropdown-item"%>
                    <%= link_to "女王グモ捕獲TA", "/explain/shrine" , class: "dropdown-item"%>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="/" id="dropdown-ranking" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">シレン2番付</a>
                <div class="dropdown-menu" aria-labelledby="dropdown-ranking">
                    <%= link_to "最果てへの道99FTA","/ranking/saihate/#{ Date.today.year.to_s + ("%02d" % Date.today.month).to_s}" , class: "dropdown-item"%>
                    <%= link_to "カラクロTA","/ranking/well/#{ Date.today.year.to_s + ("%02d" % Date.today.month).to_s}" , class: "dropdown-item"%>
                    <%= link_to "鬼ヶ島ありありTA","/ranking/onigashima/#{ Date.today.year.to_s + ("%02d" % Date.today.month).to_s}" , class: "dropdown-item"%>
                    <%= link_to "ストーリーTA","/ranking/story/#{ Date.today.year.to_s + ("%02d" % Date.today.month).to_s}" , class: "dropdown-item"%>
                    <%= link_to "女王グモ捕獲TA","/ranking/shrine/#{ Date.today.year.to_s + ("%02d" % Date.today.month).to_s}" , class: "dropdown-item"%>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <%= link_to "記録申請", newrecord_path,class: "nav-link" %>
            </li>
            <li class="nav-item">
                <% if user_signed_in?%>
                <%= link_to "マイページ", "/user/#{current_user.id}",class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: "nav-link" %>
                <% elsif %>
                <%= link_to "ログイン",new_user_session_path,class: "nav-link" %>
                <% end %>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <%= analytics_init if Rails.env.production? %>
    <%= favicon_link_tag(image_url('icons/favicon.ico')) %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= display_meta_tags(default_meta_tags) %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'home', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application'%>
    <%= javascript_include_tag "village/VillageWalk"%>
    <%= javascript_include_tag "animejs/anime.min"%>
  </head>

  <body class="d-flex flex-column" style="min-height: 100vh">
    <header>
      <%= render '/layouts/navbar_top' %>
    </header>
    <main class="mb-auto">
      <% if notice %>
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        <%= notice %>
      </div>
      <% end %>
      <% if alert %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        <%= alert %>
      </div>
      <% end %>
      <%= yield :mosttop %>
      <div id="nataneVillage" class="nataneVillage d-none d-md-block">
        <div class="nataneDungeon">
          <a href="https://com.nicovideo.jp/community/co155330" target="_blank" rel="noopener noreferrer"><img
              class="fullmoon" src=<%= image_url('nataneVillage/FullMoon.png') %>></a>
          <%= link_to "/ranking/onigashima/#{ Date.today.year.to_s + ("%02d" % Date.today.month).to_s}" do %>
          <%= image_tag image_url('nataneVillage/Onigashima.png'), { :class => "onigashima",:alt => "鬼ヶ島ありありTA",:title => "鬼ヶ島ありありTA" } %>
          <% end %>
          <%= link_to "/ranking/story/#{ Date.today.year.to_s + ("%02d" % Date.today.month).to_s}" do %>
          <%= image_tag image_url('nataneVillage/Story.png'), { :class => "story",:alt => "ストーリーTA",:title => "ストーリーTA" } %>
          <% end %>
          <%= link_to "/ranking/saihate/#{ Date.today.year.to_s + ("%02d" % Date.today.month).to_s}" do %>
          <%= image_tag image_url('nataneVillage/Mumyu.png'), { :class => "mumyu",:alt => "最果てへの道99FTA",:title => "最果てへの道99FTA" } %>
          <% end %>
          <%= link_to "/ranking/well/#{ Date.today.year.to_s + ("%02d" % Date.today.month).to_s}" do %>
          <%= image_tag image_url('nataneVillage/Well.png'), { :class => "well",:alt => "カラクロTA",:title => "カラクロTA" } %>
          <% end %>
          <%= link_to "/ranking/well/#{ Date.today.year.to_s + ("%02d" % Date.today.month).to_s}" do %>
          <%= image_tag image_url('nataneVillage/Well2.png'), { :class => "well2",:alt => "カラクロTA",:title => "カラクロTA" } %>
          <% end %>
          <%= link_to "/ranking/shrine/#{ Date.today.year.to_s + ("%02d" % Date.today.month).to_s}" do %>
          <%= image_tag image_url('nataneVillage/Shrine.png'), { :class => "shrine",:alt => "女王グモ捕獲TA" ,:title => "女王グモ捕獲TA"} %>
          <% end %>
          <%= link_to "/ranking/shrine/#{ Date.today.year.to_s + ("%02d" % Date.today.month).to_s}" do %>
          <%= image_tag image_url('nataneVillage/Shrine2.png'), { :class => "shrine2",:alt => "女王グモ捕獲TA" ,:title => "女王グモ捕獲TA" } %>
          <% end %>
          <img src=<%= image_url('nataneVillage/Road.png') %> class="road">
        </div>
        <div class="fromL">
          <div class="cloud cloudL1"></div>
          <div class="cloud cloudL2"></div>
          <div class="cloud cloudL3"></div>
          <%= link_to search_path do %>
          <div class="shirenwalk shirenL1"></div>
          <% end %>
          <div class="mamlwalk mamlL1"></div>
        </div>
        <div class="fromR">
          <div class="mamlwalk mamlR1"></div>
        </div>
      </div>
      <%= yield %>

    </main>
    <footer class="bg-dark">
      <div class="container-fluid">
        <div class="row">
          <div class="footer-left order-last order-lg-first col-12 col-lg-3 text-center">
            <a href="/">
              <%= image_tag image_url('headfoot/logo.png'), { :class => "logo", :alt => "風来のシレン2タイムアタック番付" ,:title => "風来のシレン2タイムアタック番付" } %>
            </a>
          </div>
          <div class="footer-item col-12 col-lg-3 text-center">
            <ul>
              <p>ランキング</p>
              <li>
                <%= link_to "最果てへの道99FTA", "/ranking/saihate/#{ Date.today.year.to_s + ("%02d" % Date.today.month).to_s}" %>
              </li>
              <li><%= link_to "カラクロTA", "/ranking/well/#{ Date.today.year.to_s + ("%02d" % Date.today.month).to_s}" %>
              </li>
              <li>
                <%= link_to "鬼ヶ島ありありTA", "/ranking/onigashima/#{ Date.today.year.to_s + ("%02d" % Date.today.month).to_s}" %>
              </li>
              <li><%= link_to "ストーリーTA", "/ranking/story/#{ Date.today.year.to_s + ("%02d" % Date.today.month).to_s}" %>
              </li>
              <li>
                <%= link_to "女王グモ捕獲TA", "/ranking/shrine/#{ Date.today.year.to_s + ("%02d" % Date.today.month).to_s}" %>
              </li>
            </ul>
          </div>
          <div class="footer-item col-12 col-lg-3 text-center">
            <ul>
              <p>ヘルプ</p>
              <li><a href="/description">このサイトについて</a></li>
              <li><a href="/ranking/description">記録申請について</a></li>
            </ul>
          </div>
          <div class="footer-item col-12 col-lg-3 text-center">
            <ul>
              <p>運営連絡</p>
              <li><a href="/opinion">意見箱</a></li>
              <li><a href="https://twitter.com/shiren2sougou" target="_blank" rel="noopener noreferrer">公式ツイッター</a></li>
              <li><a href="https://discord.gg/QbNu5Ku" target="_blank" rel="noopener noreferrer">公式Discordサーバー</a></li>
              <li><a href="https://com.nicovideo.jp/community/co155330" target="_blank"
                  rel="noopener noreferrer">ニコニコシレン2総合コミュニティ</a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <script>
      Village_Walk();
    </script>
  </body>

</html>

app/views/layouts/reveal.html.erb
<!doctype html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

	<title>slide</title>
	<%= stylesheet_link_tag 'application', media: 'all' %>
	<%= stylesheet_link_tag "reveal/reveal", :media => "all" %>
	<%= stylesheet_link_tag "reveal/theme/sky", :media => "all" %>

	<!-- Theme used for syntax highlighting of code -->
	<%= stylesheet_link_tag "reveal/zenburn", :media => "all" %>
	<%= stylesheet_link_tag "ta", :media => "all" %>
	<%= stylesheet_link_tag "canvasmenu/menu_topside", :media => "all" %>
	<%= stylesheet_link_tag "canvasmenu/normalize", :media => "all" %>

	<%= javascript_include_tag 'application'%>

</head>

<body>
	<div class="menu-wrap">
		<nav class="menu-top">
			<%= render '/layouts/navbar_top' %>
		</nav>
		<nav class="menu-side bg-dark">
			<a href="/ta/saihate/chapter1">1.最果て99FTAとは</a>
			<a href="/ta/saihate/chapter2">2.レベリング</a>
			<a href="/ta/saihate/chapter3">3.レベリング</a>
			<a href="/ta/saihate/chapter4">4.レベリング</a>
			<a href="/ta/saihate/chapter5">5.根田安モンスター</a>
			<a href="/ta/saihate/chapter4">6.レベリング</a>
			<a href="/ta/saihate/chapter4">7.レベリング</a>
			<a href="/ta/saihate/chapter4">8.レベリング</a>
		</nav>
	</div>
	<button class="menu-button" id="open-button">Open Menu</button>
	<div class="content-wrap">
		<%= yield %>
	</div>
	<%= javascript_include_tag "canvasmenu/classie.js" %>
	<%= javascript_include_tag "canvasmenu/main.js" %>
	<%= javascript_include_tag "revealjs/head.min.js" %>
	<%= javascript_include_tag "revealjs/reveal.js" %>
	<script>
		// More info about config & dependencies:
		// - https://github.com/hakimel/reveal.js#configuration
		// - https://github.com/hakimel/reveal.js#dependencies
		Reveal.initialize({
			controls: true,
			progress: true,
			history: false,
			center: true,
			overview: false,
			mouseWheel: true,

			transition: 'convex', // none/fade/slide/convex/concave/zoom

			// More info https://github.com/hakimel/reveal.js#dependencies
			dependencies: [
				//{ src: '/app/assets/javascripts/revealjs/classList.js', condition: function() { return !document.body.classList; } },
				//{ src: '/app/assets/javascripts/revealjs/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
				//{ src: '/app/assets/javascripts/revealjs/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
				//{ src: 'revealjs/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
				//{ src: 'revealjs/plugin/search/search.js', async: true },
				//{ src: 'revealjs/plugin/zoom-js/zoom.js', async: true },
				//{ src: 'revealjs/plugin/notes/notes.js', async: true },
				//{ src: 'revealjs/plugin/markdown/marked.js' },
				//{ src: 'revealjs/plugin/markdown/markdown.js' },
				//{ src: 'revealjs/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } }
			]
		});
	</script>
</body>

</html>